# Generated by Django 4.0.1 on 2022-02-10 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MNN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
                ('procent', models.IntegerField()),
                ('date_in', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('lek_form', models.CharField(default='tabl', max_length=300)),
                ('barcode', models.CharField(default='1234567898765', max_length=13)),
                ('name_factory', models.CharField(default='uu', max_length=255)),
                ('mnn', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='price.mnn')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_in', models.DateTimeField(blank=True, null=True)),
                ('date_out', models.DateTimeField(blank=True, null=True)),
                ('solution', models.CharField(max_length=30)),
                ('lek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.lek')),
            ],
        ),
    ]
